# Generates a header that embeds the GLSL shader files as byte arrays, so the
# shaders live in real .vert/.frag files (syntax highlighting, clean diffs) yet
# compile into the binary -- no runtime file loading, and no string-literal-size
# limit (MSVC caps a single literal at ~16KB; a byte array has no such cap).
#
# Run as a script: cmake -DSHADER_DIR=<dir> -DOUT=<header> -P embedShaders.cmake
# Each <name>.<ext> becomes sfs::shaders::<name><Ext>, e.g. quad.frag -> quadFrag.

file(GLOB shaders "${SHADER_DIR}/*.vert" "${SHADER_DIR}/*.frag")
list(SORT shaders)

set(content "// Generated by embedShaders.cmake -- do not edit.\n")
string(APPEND content "// GLSL sources from ${SHADER_DIR}, embedded as byte arrays.\n")
string(APPEND content "#pragma once\n#include <string_view>\n\nnamespace sfs::shaders\n{\n")

foreach(shader ${shaders})
  get_filename_component(base "${shader}" NAME_WE)   # quad
  get_filename_component(ext "${shader}" LAST_EXT)   # .vert
  string(SUBSTRING "${ext}" 1 1 first)               # v
  string(TOUPPER "${first}" first)                   # V
  string(SUBSTRING "${ext}" 2 -1 rest)               # ert
  set(sym "${base}${first}${rest}")                  # quadVert

  file(READ "${shader}" hex HEX)
  # static_cast keeps bytes > 0x7f (e.g. UTF-8 in comments) from tripping the
  # narrowing-to-char error in the braced initializer.
  string(REGEX REPLACE "(..)" "static_cast<char>(0x\\1)," bytes "${hex}")

  string(APPEND content "inline constexpr char ${sym}_data[] = {${bytes}0};\n")
  string(APPEND content
    "inline constexpr std::string_view ${sym}{${sym}_data, sizeof(${sym}_data) - 1};\n\n")
endforeach()

string(APPEND content "} // namespace sfs::shaders\n")

# Only rewrite when the content changed, so an unrelated rebuild doesn't touch
# the header's timestamp and recompile the renderers.
if(EXISTS "${OUT}")
  file(READ "${OUT}" existing)
  if(existing STREQUAL content)
    return()
  endif()
endif()
file(WRITE "${OUT}" "${content}")
